//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TSQL2012Entities : DbContext
    {
        public TSQL2012Entities()
            : base("name=TSQL2012Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nums> Nums { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Shippers> Shippers { get; set; }
        public virtual DbSet<Scores> Scores { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
        public virtual DbSet<EmpOrders> EmpOrders { get; set; }
        public virtual DbSet<OrderValues> OrderValues { get; set; }
    
        [DbFunction("TSQL2012Entities", "GetNums")]
        public virtual IQueryable<GetNums_Result> GetNums(Nullable<long> low, Nullable<long> high)
        {
            var lowParameter = low.HasValue ?
                new ObjectParameter("low", low) :
                new ObjectParameter("low", typeof(long));
    
            var highParameter = high.HasValue ?
                new ObjectParameter("high", high) :
                new ObjectParameter("high", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetNums_Result>("[TSQL2012Entities].[GetNums](@low, @high)", lowParameter, highParameter);
        }
    }
}
